spring:
  datasource:
    url: jdbc:mysql://0.tcp.jp.ngrok.io:12719/sm_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: newuser
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      # 개발 중엔 update, 배포 땐 validate 추천
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # 이메일 전송 설정 (Gmail 기준)
  mail:
    host: smtp.gmail.com
    port: 587
    username: dktm97@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  #날씨 API
weather:
  openweather:
    api-key: "2353758112ce6d8e849845eb674eef45"
    lat: "37.6027"     # 상명대 서울캠 근처 위도
    lon: "127.0230"    # 상명대 서울캠 근처 경도